# ============================================================
# Academic Services
# ============================================================

- role: "Conference Reviewer"
  items: "AAAI'25"

- role: "Journal Reviewer"
  items: "TCSVT, TMM, IJPRAI"
