name: Generate Gemfile.lock

on:
  workflow_dispatch: # 只允許手動觸發

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 我們需要一個特殊的 token 來允許 workflow 推送回 repo
          token: ${{ secrets.PAT }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # 這會自動執行 bundle install 並產生 lock 檔

      - name: Commit and Push Gemfile.lock
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Gemfile.lock
          # 檢查 lock 檔案是否有變動，有才 commit
          if ! git diff --staged --quiet; then
            git commit -m "ci: Generate Gemfile.lock"
            git push
          else
            echo "Gemfile.lock is already up to date."
          fi